### ISSUE TITLE
Error : 'Error in cURL request: SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by c240amg** [dyninc/dyn-php#11]
Running in windows on the command line.
PHP / composer installed
PHP Fatal error:  Uncaught exception 'Zend\Http\Client\Adapter\Exception\RuntimeException' with message 'Error in cURL request: SSL certificate problem: unable to get local issuer certificate' 
\src\dyn-php\vendor\zendframework\zend-http\src\Client\Adapter\Curl.php:422
Stack trace:
I suspect it's something to do with cacert.pem in zendesk - but don't have enough knowledge to fix.

**Comment by tfountain** [comment]
It's a while since I developed on Windows, but from some searching around the solution seems to be to download an up-to-date CA cert bundle (e.g. this one: http://curl.haxx.se/ca/cacert.pem ), put it somewhere on your filesystem, and then edit:

    curl.cainfo

in your `php.ini` file to point at this location (e.g. `curl.cainfo=C:/Windows/cacert.pem`).
